# Generated by Django 4.1 on 2022-09-02 11:49

import Expenses_tracker.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='staticfiles/images/user.png', null=True, upload_to='profiles/', validators=[Expenses_tracker.web.validators.MaxSizeInMB(5)]),
        ),
    ]
